name: Build Godot Project

on:
  push:
    branches:
      - master

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: AFungusFallGuys
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AFungusFallGuys - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}