name: Build Godot Project

on:
  push:
    branches:
      - master

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: AFungusFallGuys
          preset: windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AFungusFallGuys - windows
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}